### ISSUE TITLE
[PE-D][Tester A] Inconsistent error messages for different invalid index range in edit and delete command

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F15-1/tp#211]
The error messages for negative index and out of range index are different are of different detail level.

For `edit -1 n/Hi`:

![image.png](https://raw.githubusercontent.com/MAOXIONGKAI/ped/main/files/9edc04c6-dead-42d5-8d18-37f37716340e.png)

For `edit 10 n/Hi`:

![image.png](https://raw.githubusercontent.com/MAOXIONGKAI/ped/main/files/607463e0-499c-4f6e-9487-1cb6df5caab6.png)

The second error messages sounds a bit vague and it does not explain what exactly causes the index to be invalid, and the difference between these cases may confuse the user during the usage. A good way to fix this would be add code to handle each kind of case separately with different and more specific error message, or you can fall back and use the first one

Same goes for delete command:
For `delete -1`:

![image.png](https://raw.githubusercontent.com/MAOXIONGKAI/ped/main/files/c7d28fb2-96a6-4cbc-8606-c19f96a71dd1.png)

For `delete 10`:

![image.png](https://raw.githubusercontent.com/MAOXIONGKAI/ped/main/files/51a95fe9-28da-4c20-9598-cae45718ea41.png)

-------------
Labels: `severity.VeryLow` `type.FeatureFlaw`
original: MAOXIONGKAI/ped#2

**Comment by benjiBase** [comment]
Both messages are meant to show for different cases for the images where nurses put a -1, the error message tells nurses that the parameter of index needs to be positive as shown for both edit and delete command.
![image](https://github.com/user-attachments/assets/d9e6ca60-1e0c-4887-93cb-54577208d569)


When user key in an invalid index, it means that they have wrote an index not within GUI list as shown in our UG from the definition of Index.
![image](https://github.com/user-attachments/assets/0b2fb152-24c6-4df9-abaf-ca252f2f4ee2)
