### ISSUE TITLE
[PE-D][Tester D] Possible Feature Flaw: Priority is not "useful"

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-F15-1/tp#229]
Priority can be set or reset among the application, but would be good if there was a way to use the priority value (etc. Sorting the list by priority/Find by priority) instead of putting it as another data point.

-------------
Labels: `type.FeatureFlaw` `severity.Medium`
original: jialegitgud/ped#6

**Comment by yixianggg** [comment]
We accept the idea and have added a planned `sortpriority` feature to our planned enhancements.
