### ISSUE TITLE
[PE-D][Tester C] Ambiguous output for change priority command with wrong index

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F15-1/tp#238]
![image.png](https://raw.githubusercontent.com/clarud/ped/main/files/e11ad936-6b8e-4d3b-aaf3-35f295817b9e.png)

Error messages refer to a "patient ID," but patients are managed by an Index rather than an ID, creating potential ambiguity.

The term "ID" in error messages may confuse users, as the application and User Guide consistently use Index to refer to patient positions in the list. Replacing "ID" with "Index" in these messages would clarify the intended meaning.

-------------
Labels: `severity.Low` `type.FunctionalityBug`
original: clarud/ped#5

**Comment by yixianggg** [comment]
We accept the inconsistency. However, we see it as a feature flaw instead and have since added a fix to this flaw in out planned enhancements, to ensure consistency.
