### ISSUE TITLE
[PE-D][Tester B] Undo Redo refer to non existent addressBook

### ISSUE THREAD

**Issue by nus-pe-script** [AY2425S1-CS2103T-F15-1/tp#252]
The developer guide for **NovaCare** has planned enhancements for an **AddressBook**

![image.png](https://raw.githubusercontent.com/Timenikhil/ped/main/files/749fe6a3-e00d-4d7a-a6b6-64cfa1331b42.png)

-------------
Labels: `severity.Medium` `type.DocumentationBug`
original: Timenikhil/ped#13

**Comment by benjiBase** [comment]
added a word called AddressBook class to be more specific
