### ISSUE TITLE
[PE-D][Tester C] Result Display Box Size Limits Readability of Messages

### ISSUE THREAD

**Issue by nus-se-script** [AY2425S1-CS2103T-F15-1/tp#269]
![image.png](https://raw.githubusercontent.com/clarud/ped/main/files/cb2b0288-9e7d-4d0a-bc02-791718911d38.png)

The result display box appears too small, requiring users to scroll frequently, especially when viewing error messages or lengthy command results. This impacts the user experience, as scrolling disrupts the intended quick, CLI-based interaction.
Due to the limited size of the Result Display Box, messages often require scrolling to view fully. This could be frustrating for users, as NovaCare is designed for efficiency and speed. Increasing the display area for results could improve readability and streamline interaction, aligning better with CLI-based expectations.

-------------
Labels: `severity.Medium` `type.FeatureFlaw`
original: clarud/ped#16

**Comment by jarrellc1** [comment]
Our team decided that having a wider screen for the task and patient list is more important for nurses as they can have a larger overview of the details. The display box is merely to help nurses in case they type in a wrong command, and our correct command format is usually at the top of the error message. Only some commands require nurses to scroll continuously to the end, and we think that this will not affect the speed of nurses greatly. Fullscreen should help maximise the display box to accommodate most messages with minimal scrolling.
